export const FETCH_QUIZ_DETAIL = "FETCH_QUIZ_DETAIL";
export const FETCH_QUIZ_DETAIL_SUCCESS = "FETCH_QUIZ_DETAIL_SUCCESS";
export const FETCH_QUIZ_DETAIL_ERROR = "FETCH_QUIZ_DETAIL_ERROR";

export const SELECT_OPTION = "SELECT_OPTION";
export const GO_TO_NEXT_QUESTION = "GO_TO_NEXT_QUESTION";
export const CHECK_QUIZ_COMPLETE = "CHECK_QUIZ_COMPLETE";

export const SUBMIT_RESPONSE = "SUBMIT_RESPONSE";
export const SUBMIT_RESPONSE_SUCCESS = "SUBMIT_RESPONSE_SUCCESS";
export const SUBMIT_RESPONSE_ERROR = "SUBMIT_RESPONSE_ERROR";
